version: '3'

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'shippify'
      MYSQL_ROOT_PASSWORD: 'shippify'
      MYSQL_USER: 'shippify'
      MYSQL_PASSWORD: 'shippify'
    ports:
      - 3306:3306
